CREATE TABLE "SEC_HD_DEPARTMENTS" 
   (	"DEPARTMENT_ID" NUMBER, 
	"DEPARTMENT_NAME" VARCHAR2(50), 
	"DEPARTMENT_SHORT_CODE" VARCHAR2(4), 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_ON" DATE, 
	 CONSTRAINT "SEC_HD_DEPARTMENTS_PK" PRIMARY KEY ("DEPARTMENT_ID") ENABLE
   ) ;

CREATE TABLE "SEC_HD_DIVISIONS" 
   (	"DIVISION_ID" NUMBER, 
	"DEPARTMENT_ID" NUMBER NOT NULL ENABLE, 
	"DIVISION_NAME" VARCHAR2(50), 
	"DIVISION_SHORT_CODE" VARCHAR2(3), 
	"DIVISION_FLOOR" VARCHAR2(20), 
	"DIVISION_WING" VARCHAR2(20), 
	"DIVISION_POSITION" VARCHAR2(20), 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_ON" DATE, 
	 CONSTRAINT "SEC_HD_DIVISIONS_PK" PRIMARY KEY ("DIVISION_ID") ENABLE
   ) ;

CREATE TABLE "SEC_HD_STAFF_INFO" 
   (	"STAFF_ID" NUMBER, 
	"STAFF_INFO_TITLE" VARCHAR2(30), 
	"STAFF_INFO_LNAME" VARCHAR2(30) NOT NULL ENABLE, 
	"STAFF_INFO_FNAME" VARCHAR2(30), 
	"STAFF_INFO_GENDER" CHAR(1), 
	"STAFF_INFO_DOB" DATE, 
	"STAFF_INFO_STATE" VARCHAR2(20), 
	"STAFF_INFO_EMP_START_DATE" DATE, 
	"DEPARTMENT_ID" NUMBER, 
	"DIVISION_ID" NUMBER, 
	"STAFF_INFO_EMP_END_DATE" DATE, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_ON" DATE, 
	 CONSTRAINT "SEC_STAFF_TBL_PK" PRIMARY KEY ("STAFF_ID") ENABLE
   ) ;

CREATE TABLE "SEC_HD_STAFF" 
   (	"STAFF_ID" NUMBER, 
	"STAFF_ROLE" NUMBER NOT NULL ENABLE, 
	"STAFF_USERNAME" VARCHAR2(20) NOT NULL ENABLE, 
	"STAFF_PASSWORD" VARCHAR2(20), 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_ON" DATE, 
	 CONSTRAINT "SEC_HD_STAFF_PK" PRIMARY KEY ("STAFF_ID") ENABLE
   ) ;

CREATE TABLE "SEC_HD_TICKET_CATEGORIES" 
   (	"CATEGORY_ID" NUMBER, 
	"CATEGORY_TYPE" VARCHAR2(30), 
	"CATEGORY_NAME" VARCHAR2(50), 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_ON" DATE, 
	 CONSTRAINT "SEC_HD_TICKET_CATEGORIES_PK" PRIMARY KEY ("CATEGORY_ID") ENABLE
   ) ;

CREATE TABLE "SEC_HD_WORKTOOL_MF" 
   (	"WORKTOOL_MF_ID" NUMBER NOT NULL ENABLE, 
	"WORKTOOL_MF_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_ON" DATE, 
	 PRIMARY KEY ("WORKTOOL_MF_ID") ENABLE
   ) ;

CREATE TABLE "SEC_HD_WORKTOOL_INFORMATION" 
   (	"WORKTOOL_ID" NUMBER NOT NULL ENABLE, 
	"WORKTOOL_TYPE" VARCHAR2(20), 
	"WORKTOOL_SN" VARCHAR2(20), 
	"WORKTOOL_MF" NUMBER, 
	"WORKTOOL_MF_DATE" DATE, 
	"WORKTOOL_PURCHASE_DATE" DATE, 
	"WORKTOOL_STATUS" VARCHAR2(20), 
	"WORKTOOL_STATUS_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_ON" DATE, 
	 CONSTRAINT "SEC_HD_WORKTOOL_INFORMATIO_PK" PRIMARY KEY ("WORKTOOL_ID") ENABLE
   ) ;

CREATE TABLE "SEC_HD_TICKETS" 
   (	"TICKET_ID" NUMBER, 
	"STAFF_ID" NUMBER NOT NULL ENABLE, 
	"WORKTOOL_ID" NUMBER, 
	"CATEGORY_TYPE" VARCHAR2(30), 
	"CATEGORY_ID" NUMBER, 
	"TICKET_DESCRIPTION" VARCHAR2(500), 
	"TICKET_DATE" TIMESTAMP (6), 
	"TICKET_STATUS" VARCHAR2(20), 
	"TICKET_STATUS_DATE" TIMESTAMP (6), 
	"TICKET_STATUS_UPDATED_BY" VARCHAR2(20), 
	"TICKET_ASSIGNED_TO" VARCHAR2(20), 
	"TICKET_RESOLUTION" VARCHAR2(500), 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_ON" DATE, 
	"DIVISION_ID" NUMBER, 
	 CONSTRAINT "SEC_HD_TICKETS_PK" PRIMARY KEY ("TICKET_ID") ENABLE
   ) ;

CREATE TABLE "SEC_HD_WORKFLOWS" 
   (	"WORKFLOW_ID" NUMBER, 
	"WORKFLOW_TYPE" VARCHAR2(20), 
	"TYPE_ID" NUMBER, 
	"WORKFLOW_STATUS" VARCHAR2(20), 
	"WORKFLOW_STATUS_UPDATE" TIMESTAMP (6), 
	"WORKFLOW_STATUS_UPDATED_BY" VARCHAR2(20), 
	"WORKFLOW_CLOSED_BY" VARCHAR2(20), 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_ON" DATE, 
	 CONSTRAINT "SEC_HD_WORKFLOWS_PK" PRIMARY KEY ("WORKFLOW_ID") ENABLE
   ) ;

CREATE TABLE "SEC_HD_WORKTOOL_ALLOCATIONS" 
   (	"ALLOCATION_ID" NUMBER, 
	"WORKTOOL_ID" NUMBER, 
	"STAFF_ID" NUMBER NOT NULL ENABLE, 
	"ALLOCATION_DATE" DATE, 
	"ALLOCATION_STATUS" VARCHAR2(20), 
	"ALLOCATION_STATUS_DATE" TIMESTAMP (6), 
	"DEPARTMENT_ID" NUMBER NOT NULL ENABLE, 
	"DIVISION_ID" NUMBER NOT NULL ENABLE, 
	"ALLOCATION_TYPE" VARCHAR2(20), 
	"ALLOCATION_USE" VARCHAR2(20), 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_ON" DATE, 
	 CONSTRAINT "SEC_HD_WORKTOOL_ALLOCATION_PK" PRIMARY KEY ("ALLOCATION_ID") ENABLE
   ) ;

ALTER TABLE "SEC_HD_DIVISIONS" ADD CONSTRAINT "SEC_HD_DIVISIONS_DEPT_FK" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "SEC_HD_DEPARTMENTS" ("DEPARTMENT_ID") ENABLE;

ALTER TABLE "SEC_HD_STAFF_INFO" ADD CONSTRAINT "SEC_HD_STAFF_FK_DEPT" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "SEC_HD_DEPARTMENTS" ("DEPARTMENT_ID") ENABLE;

ALTER TABLE "SEC_HD_STAFF_INFO" ADD CONSTRAINT "SEC_HD_STAFF_FK_DIV" FOREIGN KEY ("DIVISION_ID")
	  REFERENCES "SEC_HD_DIVISIONS" ("DIVISION_ID") ENABLE;

ALTER TABLE "SEC_HD_STAFF" ADD CONSTRAINT "SEC_HD_STAFF_FK_STAFF" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "SEC_HD_STAFF_INFO" ("STAFF_ID") ENABLE;

ALTER TABLE "SEC_HD_TICKETS" ADD CONSTRAINT "SEC_HD_TICKETS_CON" FOREIGN KEY ("WORKTOOL_ID")
	  REFERENCES "SEC_HD_WORKTOOL_INFORMATION" ("WORKTOOL_ID") ENABLE;

ALTER TABLE "SEC_HD_TICKETS" ADD CONSTRAINT "SEC_HD_TICKETS_FK_CAT" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "SEC_HD_TICKET_CATEGORIES" ("CATEGORY_ID") ENABLE;

ALTER TABLE "SEC_HD_TICKETS" ADD CONSTRAINT "SEC_HD_TICKETS_FK_STAFF" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "SEC_HD_STAFF_INFO" ("STAFF_ID") ENABLE;

ALTER TABLE "SEC_HD_WORKTOOL_ALLOCATIONS" ADD CONSTRAINT "SEC_HD_WORKTOOL_ALLO_FK_WRK" FOREIGN KEY ("WORKTOOL_ID")
	  REFERENCES "SEC_HD_WORKTOOL_INFORMATION" ("WORKTOOL_ID") ENABLE;

ALTER TABLE "SEC_HD_WORKTOOL_ALLOCATIONS" ADD CONSTRAINT "SEC_HD_WORKTOOL_ALL_FK_STAFF" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "SEC_HD_STAFF_INFO" ("STAFF_ID") ENABLE;

ALTER TABLE "SEC_HD_WORKTOOL_ALLOCATIONS" ADD CONSTRAINT "SEC_HD_WRKTL_ALLO_DEPT_FK" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "SEC_HD_DEPARTMENTS" ("DEPARTMENT_ID") ENABLE;

ALTER TABLE "SEC_HD_WORKTOOL_ALLOCATIONS" ADD CONSTRAINT "SEC_HD_WRKTL_ALLO_DIV_FK" FOREIGN KEY ("DIVISION_ID")
	  REFERENCES "SEC_HD_DIVISIONS" ("DIVISION_ID") ENABLE;

ALTER TABLE "SEC_HD_WORKTOOL_INFORMATION" ADD FOREIGN KEY ("WORKTOOL_MF")
	  REFERENCES "SEC_HD_WORKTOOL_MF" ("WORKTOOL_MF_ID") ENABLE;

 CREATE SEQUENCE  "SEC_HD_WORKTOOL_MF_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

 CREATE SEQUENCE  "SEC_HD_WORKTOOL_INFORMATI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

 CREATE SEQUENCE  "SEC_HD_WORKTOOL_ALLOCATIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

 CREATE SEQUENCE  "SEC_HD_WORKFLOWS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

 CREATE SEQUENCE  "SEC_HD_TICKET_CATEGORIES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

 CREATE SEQUENCE  "SEC_HD_TICKETS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

 CREATE SEQUENCE  "SEC_HD_STAFF_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

 CREATE SEQUENCE  "SEC_HD_STAFF_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

 CREATE SEQUENCE  "SEC_HD_DIVISIONS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

 CREATE SEQUENCE  "SEC_HD_DEPARTMENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;